### ISSUE TITLE
an exception was raised in elixir 1.9.0-rc.0

### ISSUE THREAD

**Issue by bossyang** [parroty/excoveralls#189]
elixir : 1.9.0-rc.0

```
mix coveralls
** (exit) an exception was raised:
    ** (ArithmeticError) bad argument in arithmetic expression
        :erlang.+(:undefined, 0)
        (stdlib) epp.erl:1815: anonymous fn/2 in :epp.interpret_file_attr/3
        (stdlib) erl_parse.yrl:1623: anonymous fn/3 in :erl_parse.map_anno/2
        (stdlib) erl_parse.yrl:1745: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1758: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1759: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1737: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1758: :erl_parse.modify_anno1/3
    cover.erl:585: :cover.call/1
    lib/excoveralls.ex:32: ExCoveralls.start/2
    (mix) lib/mix/tasks/test.ex:407: Mix.Tasks.Test.do_run/3
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```

**Comment by bossyang** [comment]
It works in elixir 1.9.0.
