### ISSUE TITLE
Running mix task in the :dev env results in test deps not being loaded

### ISSUE THREAD

**Issue by lpil** [parroty/excoveralls#19]
Hello!

Given these deps:

```elixir
    [
      {:shouldi, only: :test},
      {:excoveralls, only: [:dev,:test]},
    ]
```

`$ mix coveralls` fails, due to `ShouldI` not being loaded in `:dev`.

```
louis ~/projects/dogma [master *] $ mix coveralls
==> idna (compile)
==> ssl_verify_hostname (compile)
==> jsx
Compiled src/jsx_decoder.erl
Compiled src/jsx_encoder.erl
Compiled src/jsx_config.erl
Compiled src/jsx_parser.erl
Compiled src/jsx.erl
Compiled src/jsx_to_term.erl
Compiled src/jsx_verify.erl
Compiled src/jsx_to_json.erl
Generated jsx app
==> exjsx
Compiled lib/jsx.ex
Generated exjsx app
==> hackney (compile)
==> excoveralls
Compiled lib/excoveralls/path_reader.ex
Compiled lib/excoveralls/post.ex
Compiled lib/excoveralls/cover.ex
Compiled lib/excoveralls.ex
Compiled lib/excoveralls/conf_server.ex
Compiled lib/excoveralls/poster.ex
Compiled lib/excoveralls/task/util.ex
Compiled lib/excoveralls/travis.ex
Compiled lib/excoveralls/stop_words.ex
Compiled lib/excoveralls/settings.ex
Compiled lib/excoveralls/stats.ex
Compiled lib/excoveralls/exceptions.ex
Compiled lib/excoveralls/local.ex
Compiled lib/mix/tasks.ex
Generated excoveralls app
==> dogma
Compiled lib/dogma/rules.ex
Compiled lib/dogma/formatter.ex
Compiled lib/dogma/error.ex
Compiled lib/dogma.ex
Compiled lib/dogma/rules/unless_else.ex
Compiled lib/dogma/rules/trailing_whitespace.ex
Compiled lib/dogma/rules/line_length.ex
Compiled lib/mix/tasks/dogma.ex
Compiled lib/dogma/formatter/simple.ex
Compiled lib/dogma/script.ex
Generated dogma app
** (CompileError) test/dogma/formatter/simple_test.exs:2: module ShouldI is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    test/dogma/formatter/simple_test.exs:2: Dogma.Formatter.SimpleTest (module)
    (elixir) lib/code.ex:307: Code.require_file/2
```

If I run it in `:test`, it works. (`MIX_ENV=test mix coveralls`)

Thanks,
Louis

**Comment by parroty** [comment]
I think it's about either adding `dev` dependency to `shouldi` or run it on `:test` environment `MIX_ENV=test mix coveralls` as you indicated.

**Comment by lpil** [comment]
It seems that adding dependancies to environments they don't really belong in isn't the most ideal solution.

**Comment by parroty** [comment]
Updating the example in the readme with `{:excoveralls, "~> 0.3", only: :test}` with `MIX_ENV=test mix coveralls` makes sense?

**Comment by zmoshansky** [comment]
@parroty I believe that's a good idea. It addresses #21 as well.

**Comment by parroty** [comment]
I'm closing this item with above commit, but if there's remaining item, please reopen or open another one.

**Comment by lpil** [comment]
Thanks. :)
