### ISSUE TITLE
Do not fail the build due to `:connection_timeout` when uploading the report

### ISSUE THREAD

**Issue by pablocostass** [parroty/excoveralls#220]
As with #112, sometimes a build will fail when uploading the coverage report due to a timeout (although this time it's due to `:connection_timeout` instead of `:timeout`).
```elixir
** (ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: connect_timeout).
    (excoveralls) lib/excoveralls/poster.ex:21: ExCoveralls.Poster.execute/2
    (mix) lib/mix/tasks/test.ex:273: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (excoveralls) lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

**Comment by pablocostass** [comment]
Closing as you merged #221.
