### ISSUE TITLE
function ExCoveralls.start/2 is undefined (module ExCoveralls is not available)

### ISSUE THREAD

**Issue by Rope-a-dope** [parroty/excoveralls#328]
I have the following mix.exs file and I verified there were excoveralls in excoveralls folder. But I tried for a few hours and couldn't figure out the reason. Anyone has the same problem?
```
** (UndefinedFunctionError) function ExCoveralls.start/2 is undefined (module ExCoveralls is not available)
    (excoveralls 0.18.2) ExCoveralls.start("/home/smallv/code/tooling/issues/_build/test/lib/issues/ebin", [export: false, output: "cover", tool: ExCoveralls])
    (mix 1.17.2) lib/mix/tasks/test.ex:559: Mix.Tasks.Test.do_run/3
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (excoveralls 0.18.2) lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /home/smallv/.local/share/mise/installs/elixir/latest/bin/mix:2: (file)
```

```
defmodule Issues.Mixfile do
  use Mix.Project

  def project do
    [
      app:             :issues,
      version:         "0.1.0",
      elixir:          "~> 1.7",
      name:            "Issues",
      source_url:      "https://github.com/pragdave/issues",
      escript:         escript_config(),
      build_embedded:  Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      test_coverage: [tool: ExCoveralls],
      preferred_cli_env: [
        coveralls: :test,
        "coveralls.detail": :test,
        "coveralls.post": :test,
        "coveralls.html": :test
      ],
      deps:            deps()
    ]
  end

  # Configuration for the OTP application
  def application do
    [
      applications: [ :logger, :httpoison ]
    ]
  end

  defp deps do
    [
      {:httpoison,  "~> 2.2"},
      {:poison,     "~> 6.0"},
      {:ex_doc,     "~> 0.34.2"},
      {:earmark,    "~> 1.4",    override: true},
      {:excoveralls, "~> 0.18.2", only: :test}
    ]
  end

  defp escript_config do
    [ main_module: Issues.CLI ]
  end

end

```

**Comment by ananthakumaran** [comment]
```
    [
      applications: [ :logger, :httpoison ]
    ]
```

This might be the reason, use extra_applications instead of directly configuring applications
