### ISSUE TITLE
Running `mix coveralls` task fails with unclean build director after source-file deletion

### ISSUE THREAD

**Issue by koos42** [parroty/excoveralls#55]
When running `mix coveralls` with a dirty build directory, one that contains beam files with missing source files, a `File.Error` is raised when `ExCoveralls.Stats. get_source_line_count` tries to count the lines of the missing source file. This is more likely with build caching set up in travis.

I would propose that these errors should be handled and displayed as either errors or warnings with a suggestion to clean any `_build` directories that are being checked.

I'm also guessing that this would happen anywhere `read_source` is called.

**Comment by parroty** [comment]
Is it possible for you to post some more details? (error message you're facing, elixir version, etc.)

I could confirm the following error with elixir v1.2.6 and tried to fix with the commit (https://github.com/parroty/excoveralls/commit/c42dc27225d8bce193769ed6011f9e40d90ffb98), but I'm not sure if it's related or not.

```elixir
excoveralls[master*]% mix test
Compiled lib/excoveralls/cover.ex
Compiled lib/excoveralls/local.ex
Compiled lib/excoveralls/stats.ex
Compiled lib/mix/tasks.ex
................................................................................

  1) test generate coverage (ExCoveralls.StatsTest)
     test/stats_test.exs:78
     ** (UndefinedFunctionError) undefined function List.Chars.BitString.to_charlist/1
     stacktrace:
       (elixir) List.Chars.BitString.to_charlist("defmodule Test do\n  def test do\n  end\nend")
       (excoveralls) lib/excoveralls/stats.ex:106: ExCoveralls.Stats.count_lines/1
       (excoveralls) lib/excoveralls/stats.ex:64: anonymous fn/2 in ExCoveralls.Stats.generate_coverage/1
       (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
       test/stats_test.exs:79

.............

  2) test get source line count (ExCoveralls.StatsTest)
     test/stats_test.exs:66
     ** (UndefinedFunctionError) undefined function List.Chars.BitString.to_charlist/1
     stacktrace:
       (elixir) List.Chars.BitString.to_charlist("defmodule Test do\n  def test do\n  end\nend")
       (excoveralls) lib/excoveralls/stats.ex:106: ExCoveralls.Stats.count_lines/1
       test/stats_test.exs:67
....

**Comment by JoshSmith** [comment]
@koos42 any updates?

**Comment by jstr** [comment]
We see this as well (I think), it looks like this:

```
** (File.Error) could not read file "/some/file.ex": no such file or directory
    (elixir) lib/file.ex:310: File.read!/1
    (excoveralls) lib/excoveralls/stats.ex:120: ExCoveralls.Stats.read_source/1
    (excoveralls) lib/excoveralls/stats.ex:102: ExCoveralls.Stats.get_source_line_count/1
    (excoveralls) lib/excoveralls/stats.ex:64: anonymous fn/2 in ExCoveralls.Stats.generate_coverage/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (excoveralls) lib/excoveralls/stats.ex:29: ExCoveralls.Stats.report/1
    (excoveralls) lib/excoveralls.ex:37: ExCoveralls.execute/2
    (mix) lib/mix/tasks/test.ex:273: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:348: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:277: Mix.Task.run/2
    (excoveralls) lib/mix/tasks.ex:51: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

Elixir 1.6.4, Excoveralls 0.8.1.
