### ISSUE TITLE
FunctionClauseError when using meck

### ISSUE THREAD

**Issue by angelikatyborska** [parroty/excoveralls#75]
I have a test suite in which for some of the tests I mock a module called `MyApp.MyProblematicModule` using meck. I am trying to use ExCoveralls for that test suite, but I am failing to even get it running.

This is the error I am getting when I try to run `mix coveralls`:
```
Randomized with seed 857085
** (FunctionClauseError) no function clause matching in List.to_string/1
    (elixir) lib/list.ex:619: List.to_string(nil)
    lib/excoveralls/cover.ex:20: ExCoveralls.Cover.module_path/1
    lib/excoveralls/stats.ex:53: ExCoveralls.Stats.add_counts/4
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/excoveralls/stats.ex:28: ExCoveralls.Stats.report/1
    lib/excoveralls.ex:35: ExCoveralls.execute/2
    (mix) lib/mix/tasks/test.ex:244: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    lib/mix/tasks.ex:53: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

To debug this issue, I added those lines to my `test_helper.exs`:
```
ExCoveralls.Cover.modules |> Enum.each(fn module ->
  IO.inspect(module.module_info(:module))
  IO.inspect(module.module_info(:compile)[:source])
end)
```

I have found that there is a module called `MyApp.MyProblematicModule_meck_original` whose source is `nil`.

My Elixir version is `1.3.2` and my ExCoveralls version is `0.5.6`.

**Comment by angelikatyborska** [comment]
It is the same for running this code in `iex`:

```
$ MIX_ENV=test iex -S mix
iex(1)> :meck.new(MyApp.MyProblematicModule) 
:ok
iex(2)> MyApp.MyProblematicModule_meck_original.module_info(:compile)
[options: [:debug_info], version: '7.0.1']
```

[Here](https://github.com/angelikatyborska/excoveralls-issue-75) is the project that I created quickly to present this problem. For [the initial commit](https://github.com/angelikatyborska/excoveralls-issue-75/tree/d6a4b10c1748005d10314b3df32dfa54a4d89336), `mix coveralls` works as expected. For [the commit that introduces meck](https://github.com/angelikatyborska/excoveralls-issue-75/tree/bb56708cd3d052f16f1b8673e3b767fbbf62484b), the issue I have reported appears.
