### ISSUE TITLE
excoveralls errors out on Erlang 19

### ISSUE THREAD

**Issue by nietaki** [parroty/excoveralls#85]
OS: `Darwin Kernel Version 15.6.0`
Erlang: `19.1`
Elixir: `1.3.4`
excoveralls: `0.5.7`

The `mix test` task runs as usual, but running `mix coveralls` or `mix coveralls.html`

Output:
```
nietaki@silver:mainframe-server (master=)$ mix coveralls
The database for Mainframe.Repo has already been created

17:51:20.966 [error] Process #PID<0.285.0> raised an exception
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])
    (stdlib) erl_parse.yrl:1516: anonymous fn/3 in :erl_parse.map_anno/2
    (stdlib) erl_parse.yrl:1645: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1658: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1637: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1658: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1648: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1658: :erl_parse.modify_anno1/3
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])
        (stdlib) erl_parse.yrl:1516: anonymous fn/3 in :erl_parse.map_anno/2
        (stdlib) erl_parse.yrl:1645: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1658: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1637: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1658: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1648: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1658: :erl_parse.modify_anno1/3
    cover.erl:583: :cover.call/1
    lib/excoveralls.ex:30: ExCoveralls.start/2
    (mix) lib/mix/tasks/test.ex:205: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:328: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:261: Mix.Task.run/2
    lib/mix/tasks.ex:53: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3


17:51:20.975 [error] Process #PID<0.284.0> raised an exception
** (ArgumentError) argument error
    (stdlib) :ets.insert(:cover_internal_clause_table, {Mainframe.Emails.Mailer.Address, [{Mainframe.Emails.Mailer.Address, :__info__, 1, 1, 1}, {Mainframe.Emails.Mailer.Address, :__info__, 1, 2, 1}, {Mainframe.Emails.Mailer.Address, :__info__, 1, 3, 1}, {Mainframe.Emails.Mailer.Address, :__struct__, 0, 1, 1}, {Mainframe.Emails.Mailer.Address, :__struct__, 1, 1, 2}]})
    cover.erl:1584: :cover.do_compile_beam2/5
    cover.erl:1478: :cover.do_compile_beam/3
    (stdlib) lists.erl:1239: :lists.map/2
    (stdlib) lists.erl:1239: :lists.map/2
    cover.erl:2732: anonymous fn/2 in :cover.pmap_spawn/4

17:51:20.975 [error] Process #PID<0.287.0> raised an exception
** (ArgumentError) argument error
    (stdlib) :ets.insert(:cover_internal_data_table, {{:bump, Mainframe.Models.Subscription, :__info__, 1, 1, 0}, 0})
    cover.erl:1789: :cover.munge_body/4
    cover.erl:1740: :cover.munge_clauses/4
    cover.erl:1719: :cover.munge/4
    cover.erl:1635: :cover.transform_2/5
    cover.erl:1620: :cover.transform/3
    cover.erl:1568: :cover.do_compile_beam2/5
    cover.erl:1478: :cover.do_compile_beam/3

17:51:20.976 [error] Process #PID<0.290.0> raised an exception
** (ArgumentError) argument error
    (stdlib) :ets.insert(:cover_internal_clause_table, {Mainframe.Uref, [{Mainframe.Uref, :__info__, 1, 1, 1}, {Mainframe.Uref, :__info__, 1, 2, 1}, {Mainframe.Uref, :__info__, 1, 3, 1}, {Mainframe.Uref, :admin_uref, 1, 1, 1}, {Mainframe.Uref, :admin_username, 1, 1, 1}, {Mainframe.Uref, :email, 2, 1, 1}, {Mainframe.Uref, :"MACRO-email_address", 2, 1, 1}, {Mainframe.Uref, :"MACRO-email_cid", 2, 1, 1}, {Mainframe.Uref, :filter_email, 1, 1, 1}, {Mainframe.Uref, :filter_native, 1, 1, 1}, {Mainframe.Uref, :format_uref, 1, 1, 1}, {Mainframe.Uref, :format_uref, 1, 2, 1}, {Mainframe.Uref, :"MACRO-is_admin?", 2, 1, 1}, {Mainframe.Uref, :"MACRO-is_email?", 2, 1, 1}, {Mainframe.Uref, :"MACRO-is_internal?", 2, 1, 1}, {Mainframe.Uref, :"MACRO-is_native?", 2, 1, 1}, {Mainframe.Uref, :"MACRO-is_system?", 2, 1, 1}, {Mainframe.Uref, :"MACRO-is_uref?", 2, 1, 1}, {Mainframe.Uref, :"MACRO-native_uid", 2, 1, 1}, {Mainframe.Uref, :parse_args, 2, 1, 1}, {Mainframe.Uref, :parse_args, 2, 2, 1}, {Mainframe.Uref, :parse_uref, 1, 1, 3}, {Mainframe.Uref, :system_uref, 0, 1, 1}, {Mainframe.Uref, :uid_to_uref, 1, 1, 1}]})
    cover.erl:1584: :cover.do_compile_beam2/5
    cover.erl:1478: :cover.do_compile_beam/3
    (stdlib) lists.erl:1239: :lists.map/2
    (stdlib) lists.erl:1239: :lists.map/2
    cover.erl:2732: anonymous fn/2 in :cover.pmap_spawn/4

17:51:20.977 [error] Process #PID<0.286.0> raised an exception
** (ArgumentError) argument error
    (stdlib) :ets.insert(:cover_internal_clause_table, {Mainframe.Models.AccountStorage, [{Mainframe.Models.AccountStorage, :__info__, 1, 1, 1}, {Mainframe.Models.AccountStorage, :__info__, 1, 2, 1}, {Mainframe.Models.AccountStorage, :__info__, 1, 3, 1}, {Mainframe.Models.AccountStorage, :__changeset__, 0, 1, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 1, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 2, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 3, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 4, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 5, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 6, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 7, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 8, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 9, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 10, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 11, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 12, 1}, {Mainframe.Models.AccountStorage, :__schema__, 1, 13, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 1, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 2, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 3, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 4, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 5, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 6, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 7, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 8, 1}, {Mainframe.Models.AccountStorage, :__schema__, 2, 9, 1}, {Mainframe.Models.AccountStorage, :__struct__, 0, 1, 1}, {Mainframe.Models.AccountStorage, :__struct__, 1, 1, 2}, {Mainframe.Models.AccountStorage, :get, 1, 1, 2}, {Mainframe.Models.AccountStorage, :get, 2, 1, 2}, {Mainframe.Models.AccountStorage, :get, 2, 2, 2}, {Mainframe.Models.AccountStorage, :set, 3, 1, 1}, {Mainframe.Models.AccountStorage, :set, 4, 1, 8}]})
    cover.erl:1584: :cover.do_compile_beam2/5
    cover.erl:1478: :cover.do_compile_beam/3
    (stdlib) lists.erl:1239: :lists.map/2
    (stdlib) lists.erl:1239: :lists.map/2
    cover.erl:2732: anonymous fn/2 in :cover.pmap_spawn/4

17:51:20.978 [error] Process #PID<0.288.0> raised an exception
** (ArgumentError) argument error
    (stdlib) :ets.insert(:cover_internal_clause_table, {Mainframe.Plug.Forwarded, [{Mainframe.Plug.Forwarded, :__info__, 1, 1, 1}, {Mainframe.Plug.Forwarded, :__info__, 1, 2, 1}, {Mainframe.Plug.Forwarded, :__info__, 1, 3, 1}, {Mainframe.Plug.Forwarded, :call, 2, 1, 7}, {Mainframe.Plug.Forwarded, :init, 1, 1, 1}, {Mainframe.Plug.Forwarded, :ip, 2, 1, 13}, {Mainframe.Plug.Forwarded, :scheme, 2, 1, 1}, {Mainframe.Plug.Forwarded, :scheme, 2, 2, 1}, {Mainframe.Plug.Forwarded, :scheme, 2, 3, 1}]})
    cover.erl:1584: :cover.do_compile_beam2/5
    cover.erl:1478: :cover.do_compile_beam/3
    (stdlib) lists.erl:1239: :lists.map/2
    (stdlib) lists.erl:1239: :lists.map/2
    cover.erl:2732: anonymous fn/2 in :cover.pmap_spawn/4


(...) - more in this vein
```

**Comment by angeldeejay** [comment]
+1

**Comment by boxxxie** [comment]
I have been running coveralls on circleCI since oct 20 with erlang 19.1, however within the past few days i get the same errors.

**Comment by parroty** [comment]
Thanks for the report (and sorry not being responsive). I assume it's same one as #60.
Please let me consolidate into this item.

**Comment by parroty** [comment]
> I have been running coveralls on circleCI since oct 20 with erlang 19.1, however within the past few days i get the same errors.

This part is somewhat weired and not indicated by other reporters. If you could share any insights about conditions, it would be helpful.
