### ISSUE TITLE
Error when running on Erlang 19.0 / Elixir 1.3.3

### ISSUE THREAD

**Issue by hazardfn** [parroty/excoveralls#86]
The coverage outputs fine but there is some kind of error in the ensure_minimum_coverage function.

```
Finished in 1.3 seconds
28 tests, 0 failures

Randomized with seed 231376
----------------
COV    FILE                                        LINES RELEVANT   MISSED
 84.9% lib/tally.ex                                  359      119       18
 80.0% lib/tally/application.ex                       29        5        1
  0.0% lib/tally/external/exchange_rates.ex           11        1        1
 60.0% lib/tally/handlers/event_handler.ex            40       15        6
 88.7% lib/tally/liability.ex                        157       53        6
  0.0% lib/tally/message/fraction.ex                  17        1        1
  0.0% lib/tally/message/keywords.ex                  19        1        1
  0.0% lib/tally/message/placement.ex                 45        1        1
  0.0% lib/tally/message/placement/selections.e       47        1        1
100.0% lib/tally/message/placement/subselection       20        1        0
  0.0% lib/tally/message/settlement.ex                67        1        1
  0.0% lib/tally/message/settlement/selections.       49        1        1
100.0% lib/tally/message/settlement/subselectio       16        1        0
 16.7% lib/tally/placement_receiver.ex                32        6        5
  0.0% lib/tally/settlement_receiver.ex               31        6        6
100.0% lib/tally/structures/id.ex                     14        1        0
  0.0% lib/tally/structures/meta.ex                   12        1        1
100.0% lib/tally/structures/tally.ex                  21        1        0
  0.0% lib/tally/structures/update.ex                 21        1        1
100.0% lib/tally/supervisor.ex                        22        2        0
 85.7% test/support/tally/producer/backend/test       42        7        1
100.0% test/support/tally/tally.ex                     5        1        0
100.0% test/support/tally/telemetry/telemetry.e       22        6        0
 88.9% test/support/tally/telemetry/telemetry/s       41        9        1
[TOTAL]  78.1%
----------------
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1636: Enum.reduce/3
    lib/excoveralls/stats.ex:209: ExCoveralls.Stats.ensure_minimum_coverage/1
    (mix) lib/mix/tasks/test.ex:244: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    lib/mix/tasks.ex:53: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I can't seem to find where it is coming from.

**Comment by dimitarvp** [comment]
With `0.6.1` I tried on Windows 10, Debian Linux, and macOS Sierra. This error was present on all 3 OS-es, only it was showing *before* the coverage was shown. It never even got to show coverage.

I was using `0.6.1` and went to `0.5.7` and that fixed it for me.

**Comment by hazardfn** [comment]
I discovered this happens when you install excoveralls as an archive and try to use it without having it as a dependency in the project too.

**Comment by parroty** [comment]
Thanks for the report (and sorry being not responsive). 
These 2 issues seem to be similar ones, and I tried fix with the above commit (it's in `master` branch).

Actually, I haven't been able to reproduce the error in my local environment. Is it possible for you to try the fix? (Maybe it's like the following).

```elixir
def deps do
  [ {:excoveralls, github: "parroty/excoveralls", only: :test} ]
end
```

If it's difficult to try, some details about conditions to reproduce is appreciated.

**Comment by dimitarvp** [comment]
@parroty That fixed it, by the way. Plan on releasing it in 0.6.2 soon?

**Comment by parroty** [comment]
Thanks for the confirmation. 
I'll be pushing to hex sometime later (as I'm out of the office today).

**Comment by dimitarvp** [comment]
Thanks for your confirmation as well. I'll be keeping an eye and upgrade to 0.6.2 when I see a new tag with that name released.

**Comment by parroty** [comment]
Pushed as v0.6.2. I'm closing this item, assuming both of the issue are fixed, but if there's remaining issue, please reopen this or open another one.

**Comment by dimitarvp** [comment]
Confirmed that the error is no longer there on a fresh install with a new project, specifying exactly version 0.6.2.

Thank you!
