### ISSUE TITLE
UndefinedFunctionError after updating hackney and excoveralls the to latest version

### ISSUE THREAD

**Issue by AndrewDryga** [parroty/excoveralls#99]
```
$ mix coveralls.travis --exclude pending
Excluding tags: [:pending]
....
Finished in 0.2 seconds
4 tests, 0 failures
Randomized with seed 797741
** (UndefinedFunctionError) function :hackney.start/0 is undefined or private. Did you mean one of:
      * start_response/1
    (hackney) :hackney.start()
    (excoveralls) lib/excoveralls/poster.ex:25: ExCoveralls.Poster.send_file/2
    (excoveralls) lib/excoveralls/poster.ex:13: ExCoveralls.Poster.execute/2
    (mix) lib/mix/tasks/test.ex:245: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:326: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:259: Mix.Task.run/2
    (excoveralls) lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
The command "mix coveralls.travis --exclude pending" exited with 1.
```

mix.lock: https://github.com/Nebo15/digital_signature.api/blob/62fa1b688dfabb542400b7ef110e18dab50caa44/mix.lock

**Comment by cabol** [comment]
I'm having the same issue with `mix coveralls.travis`, what I've found is it might be because the `hackney` dependency hasn't been updated in the `mix.lock`, currently is locked to `1.6.5`, but if you update the dependencies, `hackney` will be set to `1.8.4` and then the error comes up:

```
** (UndefinedFunctionError) function :hackney.start/0 is undefined or private. Did you mean one of:

      * start_response/1

    :hackney.start()
    lib/excoveralls/poster.ex:25: ExCoveralls.Poster.send_file/2
    lib/excoveralls/poster.ex:13: ExCoveralls.Poster.execute/2
    (mix) lib/mix/tasks/test.ex:245: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    lib/mix/tasks.ex:54: Mix.Tasks.Coveralls.do_run/2
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

This is the line that cause the error: https://github.com/parroty/excoveralls/blob/master/lib/excoveralls/poster.ex#L25

A possible fix might be replace that line by:

```elixir
Application.ensure_all_started(:hackney)
```

Thanks, stay tuned!

**Comment by parroty** [comment]
Thanks for the report and analysis, I've tried to update the code as suggested (will push to hex too).
